name: Islands
authors: [ChickenSaysBak, CozyCloud, mangoman69420, Vulcran7567]
version: ${project.version}
api-version: 1.18
depend: [FastAsyncWorldEdit, Citizens, HolographicDisplays]
main: online.cozycloud.islands.Islands
commands:
  islands:
    aliases: [is, island]
  islandsadmin:
    aliases: [isa]
    permission: islands.admin