name: Islands
authors: [ChickenSaysBak, CozyCloud, mangoman69420, Vulcran7567]
version: ${project.version}
api-version: 1.18
main: online.cozycloud.Islands.Islands
commands:
  islands:
    aliases: [is]
  islandsadmin:
    aliases: [isa]
    permission: islands.admin