name: Islanders
authors: [ChickenSaysBak, CozyCloud, mangoman69420, Vulcran7567]
version: ${project.version}
api-version: 1.19
depend: [FastAsyncWorldEdit, Citizens, HolographicDisplays]
libraries: [commons-io:commons-io:2.11.0]
main: online.cozycloud.islanders.Islanders
commands:
  islanders:
    aliases: [is, island]
  islandersadmin:
    aliases: [isa]
    permission: islanders.admin